version: '2'
services:
  python2.7:
    build:
      context: .
      dockerfile: Dockerfile.python2.7

  python3.6:
    build:
      context: .
      dockerfile: Dockerfile.python3.6

  python3.7:
    build:
      context: .
      dockerfile: Dockerfile.python3.7
