FROM lambci/lambda:build-python3.6

RUN yum -y install mysql-devel
RUN pip install -U pip setuptools

RUN mkdir -p /var/lib/iopipe

WORKDIR /var/lib/iopipe

COPY . /var/lib/iopipe

RUN python setup.py test
