service: iopipe-py-acceptance-test-serverless-layers

provider:
  name: aws
  runtime: python3.6
  stage: master
  region: us-west-2
  role: ${env:IAM_ROLE}
  environment:
    IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}

package:
  exclude:
    - ./**
  include:
    - handler.py

functions:
  py27-layer:
    environment:
        IOPIPE_HANDLER: handler.handler
    events:
      - schedule: rate(5 minutes)
    handler: iopipe.handler.wrapper
    layers:
      - arn:aws:lambda:us-west-2:146318645305:layer:IOpipePython27:2
    runtime: python2.7
  py36-layer:
    environment:
        IOPIPE_HANDLER: handler.handler
    events:
      - schedule: rate(5 minutes)
    handler: iopipe.handler.wrapper
    layers:
      - arn:aws:lambda:us-west-2:146318645305:layer:IOpipePython:2
    runtime: python3.6
  py37-layer:
    environment:
        IOPIPE_HANDLER: handler.handler
    events:
      - schedule: rate(5 minutes)
    handler: iopipe.handler.wrapper
    layers:
      - arn:aws:lambda:us-west-2:146318645305:layer:IOpipePython:2
    runtime: python3.7
